// Generated by scripts/icons/emit-glyphs.mjs from scripts/icons/icons.mjs. Do not edit by hand.
import { createIcon } from "./Icon";

/** Select · replaces lucide MousePointer2 */
export const SelectIcon = createIcon("select");
/** Pan · replaces lucide Hand */
export const PanIcon = createIcon("pan");
/** Frame · replaces lucide BoxSelect, Frame */
export const FrameIcon = createIcon("frame");
/** Rectangle · replaces lucide Square */
export const RectangleIcon = createIcon("rectangle");
/** Text · replaces lucide Type */
export const TextIcon = createIcon("text");
/** Pen · replaces lucide Pen, PenTool */
export const PenIcon = createIcon("pen");
/** Comment · replaces lucide MessageCircle */
export const CommentIcon = createIcon("comment");
/** Shader · replaces lucide ShaderIcon (custom) */
export const ShaderIcon = createIcon("shader");
/** Generate · replaces lucide Sparkles, Sparkle */
export const GenerateIcon = createIcon("generate");
/** Undo · replaces lucide Undo2 */
export const UndoIcon = createIcon("undo");
/** Redo · replaces lucide Redo2 */
export const RedoIcon = createIcon("redo");
/** Artboard · replaces lucide LayoutDashboard */
export const ArtboardIcon = createIcon("artboard");
/** Image · replaces lucide Image */
export const ImageIcon = createIcon("image");
/** Vector · replaces lucide Code2 */
export const VectorIcon = createIcon("vector");
/** Interactive surface · replaces lucide AppWindow */
export const WindowIcon = createIcon("window");
/** Visible · replaces lucide Eye */
export const EyeIcon = createIcon("eye");
/** Hidden · replaces lucide EyeOff */
export const EyeOffIcon = createIcon("eye-off");
/** Locked · replaces lucide Lock */
export const LockIcon = createIcon("lock");
/** Unlocked · replaces lucide LockOpen */
export const LockOpenIcon = createIcon("lock-open");
/** Sidebar · replaces lucide PanelLeft */
export const PanelLeftIcon = createIcon("panel-left");
/** Add · replaces lucide Plus */
export const PlusIcon = createIcon("plus");
/** Close · replaces lucide X */
export const CloseIcon = createIcon("close");
/** Check · replaces lucide Check */
export const CheckIcon = createIcon("check");
/** Delete · replaces lucide Trash2 */
export const TrashIcon = createIcon("trash");
/** Search · replaces lucide Search */
export const SearchIcon = createIcon("search");
/** Reset · replaces lucide RotateCcw */
export const ResetIcon = createIcon("reset");
/** Upload · replaces lucide Upload */
export const UploadIcon = createIcon("upload");
/** Export · replaces lucide Download */
export const DownloadIcon = createIcon("download");
/** Link · replaces lucide Link, Link2 */
export const LinkIcon = createIcon("link");
/** Unlink · replaces lucide Unlink, Unlink2 */
export const UnlinkIcon = createIcon("unlink");
/** Send · replaces lucide ArrowUp */
export const ArrowUpIcon = createIcon("arrow-up");
/** Play · replaces lucide Play */
export const PlayIcon = createIcon("play");
/** Pause · replaces lucide Pause */
export const PauseIcon = createIcon("pause");
/** Add image · replaces lucide ImagePlus */
export const ImagePlusIcon = createIcon("image-plus");
/** Loading · replaces lucide LoaderCircle */
export const LoaderIcon = createIcon("loader");
/** Warning · replaces lucide AlertTriangle */
export const AlertIcon = createIcon("alert");
/** Expand · replaces lucide ChevronDown */
export const ChevronDownIcon = createIcon("chevron-down");
/** Collapse · replaces lucide ChevronUp */
export const ChevronUpIcon = createIcon("chevron-up");
/** Disclose · replaces lucide ChevronRight */
export const ChevronRightIcon = createIcon("chevron-right");
/** Menu · replaces lucide Menu */
export const MenuIcon = createIcon("menu");
/** Corner radius · replaces lucide Squircle */
export const RadiusIcon = createIcon("radius");
/** Independent corners · replaces lucide Ungroup */
export const RadiusIndependentIcon = createIcon("radius-independent");
/** Align left · replaces lucide AlignLeft */
export const AlignTextLeftIcon = createIcon("align-text-left");
/** Align center · replaces lucide AlignCenter */
export const AlignTextCenterIcon = createIcon("align-text-center");
/** Align right · replaces lucide AlignRight */
export const AlignTextRightIcon = createIcon("align-text-right");
/** Justify · replaces lucide AlignJustify */
export const AlignTextJustifyIcon = createIcon("align-text-justify");
/** Align top · replaces lucide ArrowUpToLine */
export const ValignTopIcon = createIcon("valign-top");
/** Align middle · replaces lucide FoldVertical */
export const ValignMiddleIcon = createIcon("valign-middle");
/** Align bottom · replaces lucide ArrowDownToLine */
export const ValignBottomIcon = createIcon("valign-bottom");
/** Italic · replaces lucide Italic */
export const ItalicIcon = createIcon("italic");
/** Row · replaces lucide ArrowRightToLine */
export const DirectionRowIcon = createIcon("direction-row");
/** Column · replaces lucide ArrowDownToLine (layout) */
export const DirectionColumnIcon = createIcon("direction-column");
/** Wrap · replaces lucide TextWrap */
export const WrapIcon = createIcon("wrap");
/** Width · replaces lucide MoveHorizontal */
export const MoveHorizontalIcon = createIcon("move-horizontal");
/** Height · replaces lucide MoveVertical */
export const MoveVerticalIcon = createIcon("move-vertical");
/** Wrap in frame · replaces lucide Group */
export const FrameWrapIcon = createIcon("frame-wrap");
/** Align left edges · replaces lucide AlignStartVertical */
export const AlignLeftIcon = createIcon("align-left");
/** Align horizontal centers · replaces lucide AlignCenterVertical */
export const AlignHCenterIcon = createIcon("align-h-center");
/** Align right edges · replaces lucide AlignEndVertical */
export const AlignRightIcon = createIcon("align-right");
/** Align top edges · replaces lucide AlignStartHorizontal */
export const AlignTopIcon = createIcon("align-top");
/** Align vertical centers · replaces lucide AlignCenterHorizontal */
export const AlignVCenterIcon = createIcon("align-v-center");
/** Align bottom edges · replaces lucide AlignEndHorizontal */
export const AlignBottomIcon = createIcon("align-bottom");
/** Distribute horizontally · replaces lucide AlignHorizontalDistributeCenter */
export const DistributeHIcon = createIcon("distribute-h");
/** Distribute vertically · replaces lucide AlignVerticalDistributeCenter */
export const DistributeVIcon = createIcon("distribute-v");
/** File · replaces lucide File */
export const FileIcon = createIcon("file");
/** Folder · replaces lucide FolderOpen (closed) */
export const FolderIcon = createIcon("folder");
/** Folder open · replaces lucide FolderOpen */
export const FolderOpenIcon = createIcon("folder-open");
/** Grid view · replaces lucide Grid2x2, LayoutGrid */
export const GridIcon = createIcon("grid");
/** List view · replaces lucide List */
export const ListIcon = createIcon("list");
/** Recent · replaces lucide Clock */
export const ClockIcon = createIcon("clock");
/** Reaction · replaces lucide Smile */
export const SmileIcon = createIcon("smile");
