// Generated by scripts/icons/emit-glyphs.mjs from scripts/icons/icons.mjs. Do not edit by hand.

export interface CursorMaster {
  readonly grid: number;
  /** Hotspot in grid units, from the top-left of the image. */
  readonly hotspot: readonly [number, number];
  readonly kind: "fill" | "stroke";
  readonly stroke?: number;
  readonly body: string;
}

export const CURSOR_HALO = 2;

export const CURSORS = {
  pointer: {
    grid: 24,
    hotspot: [2, 2],
    kind: "fill",
    body: '<path d="M2 2 L21 9.6 L13.9 11.8 L11.8 13.9 L9.6 21 Z"/>',
  },
  comment: {
    grid: 24,
    hotspot: [2, 22],
    kind: "fill",
    body: '<path d="M2 22 V12 A10 10 0 1 1 12 22 Z"/>',
  },
  rotate: {
    grid: 24,
    hotspot: [12, 12],
    kind: "stroke",
    stroke: 2,
    body: '<path d="M5.7 13.54 A6 6 0 0 0 13.54 5.7"/><path d="M6.85 16.3 L5.7 13.54 L8.47 12.39 M16.3 6.85 L13.54 5.7 L12.39 8.47"/>',
  },
} as const satisfies Record<string, CursorMaster>;

export type CursorName = keyof typeof CURSORS;
