// Generated by scripts/icons/emit-glyphs.mjs from scripts/icons/icons.mjs. Do not edit by hand.

export interface GlyphMaster {
  readonly grid: 12 | 16;
  readonly stroke: number;
  /** Inner SVG markup drawn on a grid × grid viewBox with currentColor strokes and round caps. */
  readonly body: string;
}

export interface Glyph {
  readonly id: string;
  readonly name: string;
  readonly group: string;
  readonly 16: GlyphMaster;
  /** Redrawn 12-grid master; absent for glyphs that only render at 16. */
  readonly 12?: GlyphMaster;
  /** Filled twin, only where an object state has a visible hollow twin. */
  readonly filled16?: GlyphMaster;
}

export const GLYPHS = {
  select: {
    id: "select",
    name: "Select",
    group: "Tools",
    16: {
      grid: 16,
      stroke: 1.25,
      body: '<path d="M3 3 L13.5 7.2 L9.6 8.4 L8.4 9.6 L7.2 13.5 Z"/>',
    },
    12: { grid: 12, stroke: 1, body: '<path d="M2.5 2.5 L10 5.4 L7.2 6.3 L6.3 7.2 L5.4 10 Z"/>' },
  },
  pan: {
    id: "pan",
    name: "Pan",
    group: "Tools",
    16: {
      grid: 16,
      stroke: 1.25,
      body: '<path d="M3.5 8.75 V5.25 a1.5 1.5 0 0 1 3 0 V7.25 V4.25 a1.5 1.5 0 0 1 3 0 V7.25 V5.25 a1.5 1.5 0 0 1 3 0 V10.5 a4 4 0 0 1-4 4 H8.25 a4 4 0 0 1-3.2-1.6 L2.55 10.9 a1.15 1.15 0 0 1 .95-1.85 Z"/>',
    },
  },
  frame: {
    id: "frame",
    name: "Frame",
    group: "Tools",
    16: {
      grid: 16,
      stroke: 1.25,
      body: '<path d="M5.5 2 V14 M10.5 2 V14 M2 5.5 H14 M2 10.5 H14" stroke-width="1.1"/>',
    },
    12: {
      grid: 12,
      stroke: 1,
      body: '<path d="M4.5 1.5 V10.5 M7.5 1.5 V10.5 M1.5 4.5 H10.5 M1.5 7.5 H10.5"/>',
    },
  },
  rectangle: {
    id: "rectangle",
    name: "Rectangle",
    group: "Tools",
    16: { grid: 16, stroke: 1.25, body: '<rect x="2" y="2" width="12" height="12"/>' },
    12: { grid: 12, stroke: 1, body: '<rect x="1.5" y="1.5" width="9" height="9"/>' },
  },
  text: {
    id: "text",
    name: "Text",
    group: "Tools",
    16: { grid: 16, stroke: 1.25, body: '<path d="M3 4.5 V3 H13 V4.5 M8 3 V13 M5.5 13 H10.5"/>' },
    12: { grid: 12, stroke: 1, body: '<path d="M2 3.5 V2.5 H9 V3.5 M5.5 2.5 V9.5 M4 9.5 H7"/>' },
  },
  pen: {
    id: "pen",
    name: "Pen",
    group: "Tools",
    16: {
      grid: 16,
      stroke: 1.25,
      body: '<g transform="rotate(-45 8 8)"><path d="M5.75 5.75 L8 1.75 L10.25 5.75 V13 a1 1 0 0 1-1 1 H6.75 a1 1 0 0 1-1-1 Z"/><path d="M5.75 5.75 H10.25"/></g>',
    },
    12: {
      grid: 12,
      stroke: 1,
      body: '<g transform="rotate(-45 6 6)"><path d="M4.5 4.25 L6 1.5 L7.5 4.25 V9.75 a.75 .75 0 0 1-.75 .75 h-1.5 a.75 .75 0 0 1-.75-.75 Z"/><path d="M4.5 4.25 H7.5"/></g>',
    },
  },
  comment: {
    id: "comment",
    name: "Comment",
    group: "Tools",
    16: {
      grid: 16,
      stroke: 1.25,
      body: '<path d="M14 10 a2.5 2.5 0 0 1-2.5 2.5 H5.5 L2 15 V5 a2.5 2.5 0 0 1 2.5-2.5 h7 a2.5 2.5 0 0 1 2.5 2.5 Z"/>',
    },
    12: {
      grid: 12,
      stroke: 1,
      body: '<path d="M10.5 7.5 a2 2 0 0 1-2 2 H4.5 L1.5 11.5 V4.5 a2 2 0 0 1 2-2 h5 a2 2 0 0 1 2 2 Z"/>',
    },
    filled16: {
      grid: 16,
      stroke: 1.25,
      body: '<path d="M14 10 a2.5 2.5 0 0 1-2.5 2.5 H5.5 L2 15 V5 a2.5 2.5 0 0 1 2.5-2.5 h7 a2.5 2.5 0 0 1 2.5 2.5 Z" fill="currentColor"/>',
    },
  },
  shader: {
    id: "shader",
    name: "Shader",
    group: "Tools",
    16: {
      grid: 16,
      stroke: 1.25,
      body: '<rect x="2" y="2" width="12" height="12" rx="2"/><path d="M8 5 L11 8 L8 11 L5 8 Z"/>',
    },
    12: {
      grid: 12,
      stroke: 1,
      body: '<rect x="1.5" y="1.5" width="9" height="9" rx="1.5"/><path d="M6 4 L8 6 L6 8 L4 6 Z"/>',
    },
  },
  generate: {
    id: "generate",
    name: "Generate",
    group: "Tools",
    16: {
      grid: 16,
      stroke: 1.25,
      body: '<path d="M8 1.75 C8.4 5.6 10.4 7.6 14.25 8 C10.4 8.4 8.4 10.4 8 14.25 C7.6 10.4 5.6 8.4 1.75 8 C5.6 7.6 7.6 5.6 8 1.75 Z"/>',
    },
  },
  undo: {
    id: "undo",
    name: "Undo",
    group: "Tools",
    16: {
      grid: 16,
      stroke: 1.25,
      body: '<path d="M6.5 2.5 L3 6 L6.5 9.5 M3 6 H10.25 a3.25 3.25 0 0 1 0 6.5 H7.5"/>',
    },
  },
  redo: {
    id: "redo",
    name: "Redo",
    group: "Tools",
    16: {
      grid: 16,
      stroke: 1.25,
      body: '<path d="M9.5 2.5 L13 6 L9.5 9.5 M13 6 H5.75 a3.25 3.25 0 0 0 0 6.5 H8.5"/>',
    },
  },
  artboard: {
    id: "artboard",
    name: "Artboard",
    group: "Layers",
    16: {
      grid: 16,
      stroke: 1.25,
      body: '<path d="M2 5.5 V3.5 A1.5 1.5 0 0 1 3.5 2 H5.5 M10.5 2 H12.5 A1.5 1.5 0 0 1 14 3.5 V5.5 M14 10.5 V12.5 A1.5 1.5 0 0 1 12.5 14 H10.5 M5.5 14 H3.5 A1.5 1.5 0 0 1 2 12.5 V10.5"/>',
    },
    12: {
      grid: 12,
      stroke: 1,
      body: '<path d="M1.5 4 V3 A1.5 1.5 0 0 1 3 1.5 H4 M8 1.5 H9 A1.5 1.5 0 0 1 10.5 3 V4 M10.5 8 V9 A1.5 1.5 0 0 1 9 10.5 H8 M4 10.5 H3 A1.5 1.5 0 0 1 1.5 9 V8"/>',
    },
  },
  image: {
    id: "image",
    name: "Image",
    group: "Layers",
    16: {
      grid: 16,
      stroke: 1.25,
      body: '<rect x="2" y="2" width="12" height="12" rx="2"/><circle cx="10.5" cy="5.5" r="1.25"/><path d="M2 12 L5.75 8.25 a.85 .85 0 0 1 1.2 0 L12.75 14"/>',
    },
    12: {
      grid: 12,
      stroke: 1,
      body: '<rect x="1.5" y="1.5" width="9" height="9" rx="1.5"/><path d="M7.75 4.25 H8"/><path d="M1.5 9 L4.4 6.1 a.6 .6 0 0 1 .85 0 L9.5 10.5"/>',
    },
  },
  vector: {
    id: "vector",
    name: "Vector",
    group: "Layers",
    16: {
      grid: 16,
      stroke: 1.25,
      body: '<rect x="2" y="2" width="3.5" height="3.5" rx=".75"/><rect x="10.5" y="10.5" width="3.5" height="3.5" rx=".75"/><path d="M5.5 3.75 C10.5 3.75 12.25 5.5 12.25 10.5"/>',
    },
    12: {
      grid: 12,
      stroke: 1,
      body: '<rect x="1.5" y="1.5" width="3" height="3" rx=".5"/><rect x="7.5" y="7.5" width="3" height="3" rx=".5"/><path d="M4.5 3 C8 3 9 4 9 7.5"/>',
    },
  },
  window: {
    id: "window",
    name: "Interactive surface",
    group: "Layers",
    16: {
      grid: 16,
      stroke: 1.25,
      body: '<rect x="2" y="2.5" width="12" height="11" rx="2"/><path d="M2 6 H14"/>',
    },
    12: {
      grid: 12,
      stroke: 1,
      body: '<rect x="1.5" y="1.5" width="9" height="9" rx="1.5"/><path d="M1.5 4.5 H10.5"/>',
    },
  },
  eye: {
    id: "eye",
    name: "Visible",
    group: "Layers",
    16: {
      grid: 16,
      stroke: 1.25,
      body: '<path d="M1.5 8 C3.5 4.5 5.5 3 8 3 S12.5 4.5 14.5 8 C12.5 11.5 10.5 13 8 13 S3.5 11.5 1.5 8 Z"/><circle cx="8" cy="8" r="2.25"/>',
    },
    12: {
      grid: 12,
      stroke: 1,
      body: '<path d="M1 6 C2.5 3.5 4 2.5 6 2.5 S9.5 3.5 11 6 C9.5 8.5 8 9.5 6 9.5 S2.5 8.5 1 6 Z"/><circle cx="6" cy="6" r="1.5"/>',
    },
  },
  "eye-off": {
    id: "eye-off",
    name: "Hidden",
    group: "Layers",
    16: {
      grid: 16,
      stroke: 1.25,
      body: '<path d="M2.5 13.5 L13.5 2.5"/><path d="M1.5 8 C3.5 4.5 5.5 3 8 3 C8.45 3 8.85 3.05 9.25 3.15"/><path d="M13.4 6.3 C13.8 6.85 14.15 7.4 14.5 8"/><path d="M14.5 8 C12.5 11.5 10.5 13 8 13 C7.55 13 7.15 12.95 6.75 12.85"/><path d="M2.6 9.7 C2.2 9.15 1.85 8.6 1.5 8"/>',
    },
    12: {
      grid: 12,
      stroke: 1,
      body: '<path d="M2 10 L10 2"/><path d="M1 6 C2.5 3.5 4 2.5 6 2.5 C6.2 2.5 6.4 2.51 6.6 2.53"/><path d="M10.3 4.75 C10.55 5.15 10.8 5.55 11 6"/><path d="M11 6 C9.5 8.5 8 9.5 6 9.5 C5.8 9.5 5.6 9.49 5.4 9.47"/><path d="M1.7 7.25 C1.45 6.85 1.2 6.45 1 6"/>',
    },
  },
  lock: {
    id: "lock",
    name: "Locked",
    group: "Layers",
    16: {
      grid: 16,
      stroke: 1.25,
      body: '<rect x="3" y="7.5" width="10" height="6.5" rx="1.5"/><path d="M5.5 7.5 V5.5 a2.5 2.5 0 0 1 5 0 V7.5"/>',
    },
    12: {
      grid: 12,
      stroke: 1,
      body: '<rect x="2.5" y="5.5" width="7" height="5" rx="1"/><path d="M4.5 5.5 V4 a1.5 1.5 0 0 1 3 0 V5.5"/>',
    },
  },
  "lock-open": {
    id: "lock-open",
    name: "Unlocked",
    group: "Layers",
    16: {
      grid: 16,
      stroke: 1.25,
      body: '<rect x="3" y="7.5" width="10" height="6.5" rx="1.5"/><path d="M5.5 7.5 V5 a2.5 2.5 0 0 1 5 0"/>',
    },
    12: {
      grid: 12,
      stroke: 1,
      body: '<rect x="2.5" y="5.5" width="7" height="5" rx="1"/><path d="M4.5 5.5 V3.5 a1.5 1.5 0 0 1 3 0"/>',
    },
  },
  "panel-left": {
    id: "panel-left",
    name: "Sidebar",
    group: "Layers",
    16: {
      grid: 16,
      stroke: 1.25,
      body: '<rect x="2" y="2.5" width="12" height="11" rx="2"/><path d="M6.5 2.5 V13.5"/>',
    },
    12: {
      grid: 12,
      stroke: 1,
      body: '<rect x="1.5" y="1.5" width="9" height="9" rx="1.5"/><path d="M4.5 1.5 V10.5"/>',
    },
  },
  plus: {
    id: "plus",
    name: "Add",
    group: "Actions",
    16: { grid: 16, stroke: 1.25, body: '<path d="M8 3 V13 M3 8 H13"/>' },
    12: { grid: 12, stroke: 1, body: '<path d="M5.5 2 V9 M2 5.5 H9"/>' },
  },
  close: {
    id: "close",
    name: "Close",
    group: "Actions",
    16: { grid: 16, stroke: 1.25, body: '<path d="M4 4 L12 12 M12 4 L4 12"/>' },
    12: { grid: 12, stroke: 1, body: '<path d="M3 3 L9 9 M9 3 L3 9"/>' },
  },
  check: {
    id: "check",
    name: "Check",
    group: "Actions",
    16: { grid: 16, stroke: 1.25, body: '<path d="M3 8.5 L6.5 12 L13 4.5"/>' },
    12: { grid: 12, stroke: 1, body: '<path d="M2.5 6.5 L5 9 L9.5 3.5"/>' },
  },
  trash: {
    id: "trash",
    name: "Delete",
    group: "Actions",
    16: {
      grid: 16,
      stroke: 1.25,
      body: '<path d="M2.5 4.5 H13.5"/><path d="M6 4.5 V3.25 a.75 .75 0 0 1 .75-.75 h2.5 a.75 .75 0 0 1 .75 .75 V4.5"/><path d="M3.75 4.5 L4.4 13 a1.25 1.25 0 0 0 1.25 1.15 h4.7 a1.25 1.25 0 0 0 1.25-1.15 L12.25 4.5"/>',
    },
    12: {
      grid: 12,
      stroke: 1,
      body: '<path d="M2 3.5 H10"/><path d="M4.5 3.5 V2.5 a.5 .5 0 0 1 .5-.5 h2 a.5 .5 0 0 1 .5 .5 V3.5"/><path d="M3 3.5 L3.5 9.75 a1 1 0 0 0 1 .9 h3 a1 1 0 0 0 1-.9 L9 3.5"/>',
    },
  },
  search: {
    id: "search",
    name: "Search",
    group: "Actions",
    16: {
      grid: 16,
      stroke: 1.25,
      body: '<circle cx="7" cy="7" r="4.5"/><path d="M10.3 10.3 L13.5 13.5"/>',
    },
    12: {
      grid: 12,
      stroke: 1,
      body: '<circle cx="5.25" cy="5.25" r="3.5"/><path d="M7.85 7.85 L10.5 10.5"/>',
    },
  },
  reset: {
    id: "reset",
    name: "Reset",
    group: "Actions",
    16: {
      grid: 16,
      stroke: 1.25,
      body: '<path d="M2.5 8 A5.5 5.5 0 1 0 4.1 4.1"/><path d="M4.1 1.5 V4.1 H6.7"/>',
    },
    12: {
      grid: 12,
      stroke: 1,
      body: '<path d="M1.75 6 A4.25 4.25 0 1 0 3 3"/><path d="M3 1 V3 H5"/>',
    },
  },
  upload: {
    id: "upload",
    name: "Upload",
    group: "Actions",
    16: {
      grid: 16,
      stroke: 1.25,
      body: '<path d="M2.5 11 V12.5 a1 1 0 0 0 1 1 h9 a1 1 0 0 0 1-1 V11"/><path d="M8 10 V2.5 M4.5 6 L8 2.5 L11.5 6"/>',
    },
    12: {
      grid: 12,
      stroke: 1,
      body: '<path d="M1.5 8.5 V9.5 a1 1 0 0 0 1 1 h6 a1 1 0 0 0 1-1 V8.5"/><path d="M5.5 7.5 V1.5 M3 4 L5.5 1.5 L8 4"/>',
    },
  },
  download: {
    id: "download",
    name: "Export",
    group: "Actions",
    16: {
      grid: 16,
      stroke: 1.25,
      body: '<path d="M2.5 11 V12.5 a1 1 0 0 0 1 1 h9 a1 1 0 0 0 1-1 V11"/><path d="M8 2.5 V10 M4.5 6.5 L8 10 L11.5 6.5"/>',
    },
    12: {
      grid: 12,
      stroke: 1,
      body: '<path d="M1.5 8.5 V9.5 a1 1 0 0 0 1 1 h6 a1 1 0 0 0 1-1 V8.5"/><path d="M5.5 1.5 V7.5 M3 5 L5.5 7.5 L8 5"/>',
    },
  },
  link: {
    id: "link",
    name: "Link",
    group: "Actions",
    16: {
      grid: 16,
      stroke: 1.25,
      body: '<g transform="rotate(45 8 8)"><path d="M6.5 5.75 H4.75 a2.25 2.25 0 0 0 0 4.5 H6.5 M9.5 5.75 H11.25 a2.25 2.25 0 0 1 0 4.5 H9.5 M6 8 H10"/></g>',
    },
    12: {
      grid: 12,
      stroke: 1,
      body: '<g transform="rotate(45 6 6)"><path d="M5 4.25 H3.75 a1.75 1.75 0 0 0 0 3.5 H5 M7 4.25 H8.25 a1.75 1.75 0 0 1 0 3.5 H7 M4.5 6 H7.5"/></g>',
    },
  },
  unlink: {
    id: "unlink",
    name: "Unlink",
    group: "Actions",
    16: {
      grid: 16,
      stroke: 1.25,
      body: '<g transform="rotate(45 8 8)"><path d="M5.5 5.75 H3.75 a2.25 2.25 0 0 0 0 4.5 H5.5 M10.5 5.75 H12.25 a2.25 2.25 0 0 1 0 4.5 H10.5"/></g>',
    },
    12: {
      grid: 12,
      stroke: 1,
      body: '<g transform="rotate(45 6 6)"><path d="M4 4.25 H3 a1.75 1.75 0 0 0 0 3.5 H4 M8 4.25 H9 a1.75 1.75 0 0 1 0 3.5 H8"/></g>',
    },
  },
  "arrow-up": {
    id: "arrow-up",
    name: "Send",
    group: "Actions",
    16: { grid: 16, stroke: 1.25, body: '<path d="M8 13 V3 M4.5 6.5 L8 3 L11.5 6.5"/>' },
    12: { grid: 12, stroke: 1, body: '<path d="M5.5 10 V2 M3 4.5 L5.5 2 L8 4.5"/>' },
  },
  play: {
    id: "play",
    name: "Play",
    group: "Actions",
    16: { grid: 16, stroke: 1.25, body: '<path d="M5 3.5 V12.5 L12.5 8 Z"/>' },
    12: { grid: 12, stroke: 1, body: '<path d="M3.5 2.5 V9.5 L9.5 6 Z"/>' },
  },
  pause: {
    id: "pause",
    name: "Pause",
    group: "Actions",
    16: { grid: 16, stroke: 1.25, body: '<path d="M5.5 3.5 V12.5 M10.5 3.5 V12.5"/>' },
    12: { grid: 12, stroke: 1, body: '<path d="M3.5 2.5 V9.5 M7.5 2.5 V9.5"/>' },
  },
  "image-plus": {
    id: "image-plus",
    name: "Add image",
    group: "Actions",
    16: {
      grid: 16,
      stroke: 1.25,
      body: '<path d="M8 2 H4 A2 2 0 0 0 2 4 v8 a2 2 0 0 0 2 2 h8 a2 2 0 0 0 2-2 V8"/><path d="M12.5 1.5 V5.5 M10.5 3.5 H14.5"/><path d="M2 12 L5.75 8.25 a.85 .85 0 0 1 1.2 0 L12.75 14"/>',
    },
    12: {
      grid: 12,
      stroke: 1,
      body: '<path d="M6 1.5 H3 A1.5 1.5 0 0 0 1.5 3 v6 a1.5 1.5 0 0 0 1.5 1.5 h6 a1.5 1.5 0 0 0 1.5-1.5 V6"/><path d="M9.5 1 V4 M8 2.5 H11"/><path d="M1.5 9 L4.4 6.1 a.6 .6 0 0 1 .85 0 L9.5 10.5"/>',
    },
  },
  loader: {
    id: "loader",
    name: "Loading",
    group: "Actions",
    16: { grid: 16, stroke: 1.25, body: '<path d="M8 2 A6 6 0 1 1 2 8"/>' },
    12: { grid: 12, stroke: 1, body: '<path d="M6 1.5 A4.5 4.5 0 1 1 1.5 6"/>' },
  },
  alert: {
    id: "alert",
    name: "Warning",
    group: "Actions",
    16: {
      grid: 16,
      stroke: 1.25,
      body: '<path d="M6.9 3.4 L1.9 12.2 A1.25 1.25 0 0 0 3 14 h10 a1.25 1.25 0 0 0 1.1-1.85 L9.1 3.4 a1.25 1.25 0 0 0-2.2 0 Z"/><path d="M8 6.5 V9.25 M8 11.5 V11.75"/>',
    },
    12: {
      grid: 12,
      stroke: 1,
      body: '<path d="M5.15 2.55 L1.4 9.1 A.95 .95 0 0 0 2.25 10.5 h7.5 a.95 .95 0 0 0 .85-1.4 L6.85 2.55 a.95 .95 0 0 0-1.7 0 Z"/><path d="M6 4.75 V6.75 M6 8.4 V8.65"/>',
    },
  },
  "chevron-down": {
    id: "chevron-down",
    name: "Expand",
    group: "Disclosure",
    16: { grid: 16, stroke: 1.25, body: '<path d="M4 6 L8 10 L12 6"/>' },
    12: { grid: 12, stroke: 1, body: '<path d="M3 4.5 L6 7.5 L9 4.5"/>' },
  },
  "chevron-up": {
    id: "chevron-up",
    name: "Collapse",
    group: "Disclosure",
    16: { grid: 16, stroke: 1.25, body: '<path d="M4 10 L8 6 L12 10"/>' },
    12: { grid: 12, stroke: 1, body: '<path d="M3 7.5 L6 4.5 L9 7.5"/>' },
  },
  "chevron-right": {
    id: "chevron-right",
    name: "Disclose",
    group: "Disclosure",
    16: { grid: 16, stroke: 1.25, body: '<path d="M6 4 L10 8 L6 12"/>' },
    12: { grid: 12, stroke: 1, body: '<path d="M4.5 3 L7.5 6 L4.5 9"/>' },
  },
  menu: {
    id: "menu",
    name: "Menu",
    group: "Disclosure",
    16: { grid: 16, stroke: 1.25, body: '<path d="M2.5 4 H13.5 M2.5 8 H13.5 M2.5 12 H13.5"/>' },
    12: { grid: 12, stroke: 1, body: '<path d="M1.5 2.5 H10.5 M1.5 5.5 H10.5 M1.5 8.5 H10.5"/>' },
  },
  radius: {
    id: "radius",
    name: "Corner radius",
    group: "Properties",
    16: { grid: 16, stroke: 1.25, body: '<path d="M3 13 V8 A5 5 0 0 1 8 3 H13"/>' },
    12: { grid: 12, stroke: 1, body: '<path d="M2.5 10 V6.5 A4 4 0 0 1 6.5 2.5 H10"/>' },
  },
  "radius-independent": {
    id: "radius-independent",
    name: "Independent corners",
    group: "Properties",
    16: {
      grid: 16,
      stroke: 1.25,
      body: '<path d="M2.5 6 A3.5 3.5 0 0 1 6 2.5 M10 2.5 A3.5 3.5 0 0 1 13.5 6 M13.5 10 A3.5 3.5 0 0 1 10 13.5 M6 13.5 A3.5 3.5 0 0 1 2.5 10"/>',
    },
    12: {
      grid: 12,
      stroke: 1,
      body: '<path d="M1.5 4.5 A3 3 0 0 1 4.5 1.5 M7.5 1.5 A3 3 0 0 1 10.5 4.5 M10.5 7.5 A3 3 0 0 1 7.5 10.5 M4.5 10.5 A3 3 0 0 1 1.5 7.5"/>',
    },
  },
  "align-text-left": {
    id: "align-text-left",
    name: "Align left",
    group: "Properties",
    16: { grid: 16, stroke: 1.25, body: '<path d="M2.5 4 H13.5 M2.5 8 H9.5 M2.5 12 H11.5"/>' },
    12: { grid: 12, stroke: 1, body: '<path d="M1.5 2.5 H10.5 M1.5 5.5 H7.5 M1.5 8.5 H9"/>' },
  },
  "align-text-center": {
    id: "align-text-center",
    name: "Align center",
    group: "Properties",
    16: { grid: 16, stroke: 1.25, body: '<path d="M2.5 4 H13.5 M4.5 8 H11.5 M3.5 12 H12.5"/>' },
    12: { grid: 12, stroke: 1, body: '<path d="M1.5 2.5 H10.5 M3 5.5 H9 M2.25 8.5 H9.75"/>' },
  },
  "align-text-right": {
    id: "align-text-right",
    name: "Align right",
    group: "Properties",
    16: { grid: 16, stroke: 1.25, body: '<path d="M2.5 4 H13.5 M6.5 8 H13.5 M4.5 12 H13.5"/>' },
    12: { grid: 12, stroke: 1, body: '<path d="M1.5 2.5 H10.5 M4.5 5.5 H10.5 M3 8.5 H10.5"/>' },
  },
  "align-text-justify": {
    id: "align-text-justify",
    name: "Justify",
    group: "Properties",
    16: { grid: 16, stroke: 1.25, body: '<path d="M2.5 4 H13.5 M2.5 8 H13.5 M2.5 12 H13.5"/>' },
    12: { grid: 12, stroke: 1, body: '<path d="M1.5 2.5 H10.5 M1.5 5.5 H10.5 M1.5 8.5 H10.5"/>' },
  },
  "valign-top": {
    id: "valign-top",
    name: "Align top",
    group: "Properties",
    16: {
      grid: 16,
      stroke: 1.25,
      body: '<path d="M3 2.5 H13"/><path d="M8 13.5 V6 M4.5 9.5 L8 6 L11.5 9.5"/>',
    },
    12: {
      grid: 12,
      stroke: 1,
      body: '<path d="M2 1.5 H9"/><path d="M5.5 10.5 V4.5 M3 7 L5.5 4.5 L8 7"/>',
    },
  },
  "valign-middle": {
    id: "valign-middle",
    name: "Align middle",
    group: "Properties",
    16: {
      grid: 16,
      stroke: 1.25,
      body: '<path d="M2 8 H4.25 M6.75 8 H9.25 M11.75 8 H14"/><path d="M8 2 V5.5 M6 3.75 L8 5.5 L10 3.75"/><path d="M8 14 V10.5 M6 12.25 L8 10.5 L10 12.25"/>',
    },
    12: {
      grid: 12,
      stroke: 1,
      body: '<path d="M1 5.5 H2.5 M4.5 5.5 H6.5 M8.5 5.5 H10"/><path d="M5.5 1 V3.5 M4 2 L5.5 3.5 L7 2"/><path d="M5.5 10 V7.5 M4 9 L5.5 7.5 L7 9"/>',
    },
  },
  "valign-bottom": {
    id: "valign-bottom",
    name: "Align bottom",
    group: "Properties",
    16: {
      grid: 16,
      stroke: 1.25,
      body: '<path d="M3 13.5 H13"/><path d="M8 2.5 V10 M4.5 6.5 L8 10 L11.5 6.5"/>',
    },
    12: {
      grid: 12,
      stroke: 1,
      body: '<path d="M2 10.5 H9"/><path d="M5.5 1.5 V7.5 M3 5 L5.5 7.5 L8 5"/>',
    },
  },
  italic: {
    id: "italic",
    name: "Italic",
    group: "Properties",
    16: { grid: 16, stroke: 1.25, body: '<path d="M9.5 3 H13 M3 13 H6.5 M10 3 L6 13"/>' },
    12: { grid: 12, stroke: 1, body: '<path d="M7 2.5 H9.5 M2.5 9.5 H5 M7.5 2.5 L4.5 9.5"/>' },
  },
  "direction-row": {
    id: "direction-row",
    name: "Row",
    group: "Properties",
    16: { grid: 16, stroke: 1.25, body: '<path d="M2.5 8 H13.5 M10 4.5 L13.5 8 L10 11.5"/>' },
    12: { grid: 12, stroke: 1, body: '<path d="M1.5 5.5 H10 M7.5 3 L10 5.5 L7.5 8"/>' },
  },
  "direction-column": {
    id: "direction-column",
    name: "Column",
    group: "Properties",
    16: { grid: 16, stroke: 1.25, body: '<path d="M8 2.5 V13.5 M4.5 10 L8 13.5 L11.5 10"/>' },
    12: { grid: 12, stroke: 1, body: '<path d="M5.5 1.5 V10 M3 7.5 L5.5 10 L8 7.5"/>' },
  },
  wrap: {
    id: "wrap",
    name: "Wrap",
    group: "Properties",
    16: {
      grid: 16,
      stroke: 1.25,
      body: '<path d="M2.5 4 H13.5 M2.5 8 H11 a2 2 0 0 1 0 4 H9 M10.5 10.5 L9 12 L10.5 13.5 M2.5 12 H5.5"/>',
    },
    12: {
      grid: 12,
      stroke: 1,
      body: '<path d="M1.5 2.5 H10.5 M1.5 5.5 H8.5 a1.5 1.5 0 0 1 0 3 H7 M8 7.5 L7 8.5 L8 9.5 M1.5 8.5 H3.5"/>',
    },
  },
  "move-horizontal": {
    id: "move-horizontal",
    name: "Width",
    group: "Properties",
    16: {
      grid: 16,
      stroke: 1.25,
      body: '<path d="M2 8 H14 M5.5 4.5 L2 8 L5.5 11.5 M10.5 4.5 L14 8 L10.5 11.5"/>',
    },
    12: {
      grid: 12,
      stroke: 1,
      body: '<path d="M1.5 5.5 H10.5 M4 3 L1.5 5.5 L4 8 M8 3 L10.5 5.5 L8 8"/>',
    },
  },
  "move-vertical": {
    id: "move-vertical",
    name: "Height",
    group: "Properties",
    16: {
      grid: 16,
      stroke: 1.25,
      body: '<path d="M8 2 V14 M4.5 5.5 L8 2 L11.5 5.5 M4.5 10.5 L8 14 L11.5 10.5"/>',
    },
    12: {
      grid: 12,
      stroke: 1,
      body: '<path d="M5.5 1.5 V10.5 M3 4 L5.5 1.5 L8 4 M3 8 L5.5 10.5 L8 8"/>',
    },
  },
  "frame-wrap": {
    id: "frame-wrap",
    name: "Wrap in frame",
    group: "Properties",
    16: {
      grid: 16,
      stroke: 1.25,
      body: '<path d="M2 5.5 V3.5 A1.5 1.5 0 0 1 3.5 2 H5.5 M10.5 2 H12.5 A1.5 1.5 0 0 1 14 3.5 V5.5 M14 10.5 V12.5 A1.5 1.5 0 0 1 12.5 14 H10.5 M5.5 14 H3.5 A1.5 1.5 0 0 1 2 12.5 V10.5"/><rect x="5.75" y="5.75" width="4.5" height="4.5" rx="1"/>',
    },
    12: {
      grid: 12,
      stroke: 1,
      body: '<path d="M1.5 4 V3 A1.5 1.5 0 0 1 3 1.5 H4 M8 1.5 H9 A1.5 1.5 0 0 1 10.5 3 V4 M10.5 8 V9 A1.5 1.5 0 0 1 9 10.5 H8 M4 10.5 H3 A1.5 1.5 0 0 1 1.5 9 V8"/><rect x="4.5" y="4.5" width="3" height="3" rx=".5"/>',
    },
  },
  "align-left": {
    id: "align-left",
    name: "Align left edges",
    group: "Alignment",
    16: {
      grid: 16,
      stroke: 1.25,
      body: '<path d="M2.5 2 V14"/><rect x="5" y="3.5" width="8.5" height="3" rx="1"/><rect x="5" y="9.5" width="5.5" height="3" rx="1"/>',
    },
  },
  "align-h-center": {
    id: "align-h-center",
    name: "Align horizontal centers",
    group: "Alignment",
    16: {
      grid: 16,
      stroke: 1.25,
      body: '<path d="M8 2 V3.5 M8 6.5 V9.5 M8 12.5 V14"/><rect x="3" y="3.5" width="10" height="3" rx="1"/><rect x="5" y="9.5" width="6" height="3" rx="1"/>',
    },
  },
  "align-right": {
    id: "align-right",
    name: "Align right edges",
    group: "Alignment",
    16: {
      grid: 16,
      stroke: 1.25,
      body: '<path d="M13.5 2 V14"/><rect x="2.5" y="3.5" width="8.5" height="3" rx="1"/><rect x="5.5" y="9.5" width="5.5" height="3" rx="1"/>',
    },
  },
  "align-top": {
    id: "align-top",
    name: "Align top edges",
    group: "Alignment",
    16: {
      grid: 16,
      stroke: 1.25,
      body: '<path d="M2 2.5 H14"/><rect x="3.5" y="5" width="3" height="8.5" rx="1"/><rect x="9.5" y="5" width="3" height="5.5" rx="1"/>',
    },
  },
  "align-v-center": {
    id: "align-v-center",
    name: "Align vertical centers",
    group: "Alignment",
    16: {
      grid: 16,
      stroke: 1.25,
      body: '<path d="M2 8 H3.5 M6.5 8 H9.5 M12.5 8 H14"/><rect x="3.5" y="3" width="3" height="10" rx="1"/><rect x="9.5" y="5" width="3" height="6" rx="1"/>',
    },
  },
  "align-bottom": {
    id: "align-bottom",
    name: "Align bottom edges",
    group: "Alignment",
    16: {
      grid: 16,
      stroke: 1.25,
      body: '<path d="M2 13.5 H14"/><rect x="3.5" y="2.5" width="3" height="8.5" rx="1"/><rect x="9.5" y="5.5" width="3" height="5.5" rx="1"/>',
    },
  },
  "distribute-h": {
    id: "distribute-h",
    name: "Distribute horizontally",
    group: "Alignment",
    16: {
      grid: 16,
      stroke: 1.25,
      body: '<path d="M2 2.5 V13.5 M14 2.5 V13.5"/><path d="M5.75 5 V11 M10.25 5 V11"/>',
    },
  },
  "distribute-v": {
    id: "distribute-v",
    name: "Distribute vertically",
    group: "Alignment",
    16: {
      grid: 16,
      stroke: 1.25,
      body: '<path d="M2.5 2 H13.5 M2.5 14 H13.5"/><path d="M5 5.75 H11 M5 10.25 H11"/>',
    },
  },
  file: {
    id: "file",
    name: "File",
    group: "Files",
    16: {
      grid: 16,
      stroke: 1.25,
      body: '<path d="M9.5 2 H4.5 A1.5 1.5 0 0 0 3 3.5 v9 A1.5 1.5 0 0 0 4.5 14 h7 a1.5 1.5 0 0 0 1.5-1.5 V5.5 Z"/><path d="M9.5 2 V5.5 H13"/>',
    },
    12: {
      grid: 12,
      stroke: 1,
      body: '<path d="M7 1.5 H4 A1.5 1.5 0 0 0 2.5 3 v6 A1.5 1.5 0 0 0 4 10.5 h4 a1.5 1.5 0 0 0 1.5-1.5 V4 Z"/><path d="M7 1.5 V4 H9.5"/>',
    },
  },
  folder: {
    id: "folder",
    name: "Folder",
    group: "Files",
    16: {
      grid: 16,
      stroke: 1.25,
      body: '<path d="M2 4.5 a1.5 1.5 0 0 1 1.5-1.5 h3 l1.5 1.5 h5.5 a1.5 1.5 0 0 1 1.5 1.5 v6.5 a1.5 1.5 0 0 1-1.5 1.5 h-10 A1.5 1.5 0 0 1 2 12.5 Z"/>',
    },
  },
  "folder-open": {
    id: "folder-open",
    name: "Folder open",
    group: "Files",
    16: {
      grid: 16,
      stroke: 1.25,
      body: '<path d="M2 8 V4.5 a1.5 1.5 0 0 1 1.5-1.5 h3 l1.5 1.5 h4.5 a1.5 1.5 0 0 1 1.5 1.5 V7"/><path d="M2 13.5 L3.6 8.4 a1.2 1.2 0 0 1 1.15-.85 H14 a.9 .9 0 0 1 .86 1.16 L13.5 13 a1.2 1.2 0 0 1-1.15 .85 H3 A1 1 0 0 1 2 13.5 Z"/>',
    },
  },
  grid: {
    id: "grid",
    name: "Grid view",
    group: "Files",
    16: {
      grid: 16,
      stroke: 1.25,
      body: '<rect x="2" y="2" width="4.5" height="4.5" rx="1.25"/><rect x="9.5" y="2" width="4.5" height="4.5" rx="1.25"/><rect x="2" y="9.5" width="4.5" height="4.5" rx="1.25"/><rect x="9.5" y="9.5" width="4.5" height="4.5" rx="1.25"/>',
    },
    12: {
      grid: 12,
      stroke: 1,
      body: '<rect x="1.5" y="1.5" width="3" height="3" rx=".75"/><rect x="7.5" y="1.5" width="3" height="3" rx=".75"/><rect x="1.5" y="7.5" width="3" height="3" rx=".75"/><rect x="7.5" y="7.5" width="3" height="3" rx=".75"/>',
    },
  },
  list: {
    id: "list",
    name: "List view",
    group: "Files",
    16: {
      grid: 16,
      stroke: 1.25,
      body: '<path d="M2.75 4 H3 M2.75 8 H3 M2.75 12 H3"/><path d="M6.5 4 H13.5 M6.5 8 H13.5 M6.5 12 H13.5"/>',
    },
    12: {
      grid: 12,
      stroke: 1,
      body: '<path d="M1.5 2.5 H1.75 M1.5 5.5 H1.75 M1.5 8.5 H1.75"/><path d="M4.5 2.5 H10.5 M4.5 5.5 H10.5 M4.5 8.5 H10.5"/>',
    },
  },
  clock: {
    id: "clock",
    name: "Recent",
    group: "Files",
    16: { grid: 16, stroke: 1.25, body: '<circle cx="8" cy="8" r="6"/><path d="M8 4.5 V8 H11"/>' },
    12: { grid: 12, stroke: 1, body: '<circle cx="6" cy="6" r="4.5"/><path d="M6 3.5 V6 H8"/>' },
  },
  smile: {
    id: "smile",
    name: "Reaction",
    group: "Files",
    16: {
      grid: 16,
      stroke: 1.25,
      body: '<circle cx="8" cy="8" r="6"/><path d="M5.75 6.5 H6 M10 6.5 H10.25"/><path d="M5.5 9.5 a2.5 2.5 0 0 0 5 0"/>',
    },
    12: {
      grid: 12,
      stroke: 1,
      body: '<circle cx="6" cy="6" r="4.5"/><path d="M4.25 4.75 H4.5 M7.5 4.75 H7.75"/><path d="M4 7 a2 2 0 0 0 4 0"/>',
    },
  },
} as const satisfies Record<string, Glyph>;

export type IconName = keyof typeof GLYPHS;
